# Generated by Django 5.1.7 on 2025-04-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('FF', 'Fast-Food'), ('IN', 'Indian'), ('HE', 'Healthy'), ('DE', 'Desserts'), ('RE', 'Refreshers')], max_length=2)),
                ('product_img', models.ImageField(upload_to='product')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
