# Generated by Django 5.1.7 on 2025-04-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_payment_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_order_id',
            new_name='stripe_order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_payment_id',
            new_name='stripe_payment_intent',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_payment_status',
        ),
    ]
